services:
  max-gateway:
    build: https://github.com/dmansurov83/max-api-gateway.git#master
    image: max-gateway:latest
    container_name: max-gateway
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MAX_TOKEN=${MAX_TOKEN}
      - MAX_DEVICE_ID=${MAX_DEVICE_ID}
      - API_TOKEN=${API_TOKEN:-my_secret_api_token}
      - PORT=8000
    volumes:
      - ./config.yaml:/config.yaml:ro